<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <ApplicationId>com.michaeloborne.missionplanner</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <AndroidManifest>Properties/AndroidManifest.xml</AndroidManifest>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <RuntimeIdentifiers>android-arm64</RuntimeIdentifiers>
    <RuntimeIdentifier>android-arm64</RuntimeIdentifier>
    <AndroidEnableJetifier>true</AndroidEnableJetifier>
    <AndroidUseAndroidX>true</AndroidUseAndroidX>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Xamarin/Xamarin.csproj" />
    <ProjectReference Include="../../ArduPilot/MissionPlanner.ArduPilot.csproj" />
    <ProjectReference Include="../../Comms/MissionPlanner.Comms.csproj" />
    <ProjectReference Include="../../GMap.NET.Core/GMap.NET.Core.csproj" />
    <ProjectReference Include="../../Interfaces/Interfaces.csproj" />
    <ProjectReference Include="../../MissionPlanner.Drawing/MissionPlanner.Drawing.csproj" />
    <ProjectReference Include="../../UsbSerialForAndroid/UsbSerialForAndroid.csproj" />
    <ProjectReference Include="../../Utilities/MissionPlanner.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SkiaSharp.Views.Forms" Version="2.80.2" />
    <PackageReference Include="Xamarin.Essentials" Version="1.8.1" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2662" />
    <PackageReference Include="Xamarin.Google.Guava.ListenableFuture" Version="1.0.0.15" ExcludeAssets="all" />
  </ItemGroup>
</Project>